Name: Build
on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Package name of the game:"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Cập nhật từ v3 -> v4
    - uses: actions/checkout@v4

    # Cập nhật từ v3 -> v4 (Hỗ trợ Java 21 và các bản vá mới nhất)
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17' # Bạn nên cân nhắc lên Java 17 nếu Gradle của bạn hỗ trợ
        cache: 'gradle'

    - name: Prepare and Build
      run: |
        chmod +x ./gradlew
        # Sử dụng sed để thay thế thông tin package
        sed -i 's/moduleDescription = "/moduleDescription = "(${{ github.event.inputs.package_name }}) /g' module.gradle
        sed -i "s/com.game.packagename/${{ github.event.inputs.package_name }}/g" module/src/main/cpp/game.h
        ./gradlew :module:assembleRelease

    # Cập nhật từ v3 -> v4 (Tốc độ upload nhanh hơn, nén tốt hơn)
    - uses: actions/upload-artifact@v4
      with:
        name: zygisk-il2cppdumper-${{ github.event.inputs.package_name }} # Thêm tên package để dễ phân biệt
        path: out/magisk_module_release/
        
